apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: coraza-waf
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  url: "oci://ghcr.io/corazawaf/coraza-proxy-wasm:v1.0.0"
  imagePullPolicy: IfNotPresent
  phase: AUTHN
  pluginConfig:
    default_directives: "default"
    directives_map:
      default:
        # Enable Coraza rules
        - "SecRuleEngine On"
        # Exclude /health path from scanning
        - 'SecRule REQUEST_URI "@beginsWith /health" "id:1000,phase:1,pass,nolog,ctl:ruleEngine=Off"'
        # Recommended default rules
        - "Include @recommended-conf"
        - "Include @crs-setup-conf"
        - "Include @owasp_crs/*.conf"
        # Enable audit logs to stdout (Kubernetes will capture them)
        - "SecAuditEngine RelevantOnly"
        - "SecAuditLogType Serial"
        - "SecAuditLog /dev/stdout"
        - "SecAuditLogFormat JSON"
        # Optional: debug level 0 (production)
        - "SecDebugLogLevel 0"
