apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: coraza-waf
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  url: "oci://ghcr.io/corazawaf/coraza-proxy-wasm:v1.0.0"
  imagePullPolicy: IfNotPresent
  phase: AUTHN
  pluginConfig:
    default_directives: "default"
    directives_map:
      default:
        - "Include @recommended-conf"
        - "SecRuleEngine On"
        - "SecDebugLogLevel 0"
        - "Include @crs-setup-conf"
        - "Include @owasp_crs/*.conf"
