apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: coraza-waf
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  url: "ghcr.io/corazawaf/coraza-proxy-wasm:0.6.0"
  imagePullPolicy: IfNotPresent
  phase: AUTHZ
  priority: 1000
  failStrategy: FAIL_CLOSE # Options are FAIL_RELOAD | FAIL_OPEN | FAIL_CLOSE
  pluginConfig:
    requestBodyAccess: true
    processInvalidRequests: true
    # This is the correct format for v0.6.0
    rules: |
      SecDebugLogLevel 1
      SecAuditEngine RelevantOnly
      SecAuditLog /dev/stdout
      SecAuditEngine Off
      SecAuditLogParts ABCFHZ
      SecAuditLogFormat JSON

      # SecRequestBodyAccess On
      # SecRequestBodyLimit 13107200          # 12.5 MB
      # SecRequestBodyInMemoryLimit 131072    # 128 KB
      # SecRequestBodyNoFilesLimit 13107200
      # SecRequestBodyLimitAction ProcessPartial

      # SecResponseBodyAccess On
      # SecResponseBodyLimit 5242880          # 5 MB
      # SecResponseBodyInMemoryLimit 524288

      Include @crs-setup-conf
      Include @owasp_crs/*.conf

      # Rule 1 (ID 101)
      SecRule ARGS:testblock "@eq true" "id:101,phase:2,deny,status:403,msg:'WAF TEST BLOCK'"

      # Rule 1 (ID 200100)
      SecRule ARGS "(?i)(http?|https?|ftp)://[^\s]+" "id:200100,phase:2,deny,status:403,msg:'RFI Detected'"

      # *** NEW RULE TO ENABLE LOGGING ONLY ON BLOCK ***
      # In the logging phase (5), this rule checks if the request was blocked.
      # If TX.INTERVENTION is "1" (meaning blocked), it turns the audit engine ON
      # just for this single transaction. Formatting will revert back to basic text
      SecRule TX:INTERVENTION "@eq 1" "id:999,phase:5,pass,nolog,ctl:auditEngine=On"
