apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: coraza-waf
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  url: "ghcr.io/corazawaf/coraza-proxy-wasm:0.6.0"
  imagePullPolicy: IfNotPresent
  phase: AUTHN
  priority: 1000
  failStrategy: FAIL_CLOSE # Options are FAIL_RELOAD | FAIL_OPEN | FAIL_CLOSE
  pluginConfig:
    # This is the correct format for v0.6.0
    rules: |
      SecDebugLogLevel 4
      SecAuditLog /dev/stdout
      SecAuditLogParts ABCFHZ
      SecAuditLogFormat JSON
      SecRuleEngine On
      Include @crs-setup-conf
      Include @owasp_crs/*.conf

      # Rule 1 (ID 101)
      # curl -I -v "https://my-application/?testblock=true"
      SecRule ARGS:testblock "@eq true" "id:1001,phase:2,deny,status:403,msg:'WAF TEST BLOCK'"

      SecRule REQUEST_URI "@beginsWith /health" "id:1000,phase:1,pass,nolog,ctl:ruleEngine=Off"'
