Helm Template for KEDA ScaledObject

```yaml
{{- if .Values.keda.enabled }}

---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "mychart.name" . }}-trigger-authentication
spec:
  podIdentity:
    provider: aws
    roleArn: {{ required "triggerAuthentication.roleArn is required." .Values.triggerAuthentication.roleArn }}
---

{{- with .Values.scaledObjects }}
{{- if or (not (hasKey . "enabled")) .enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "common.names.fullname" $ }}-scaledobject
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "mychart.labels" $ | nindent 4 }}
spec:
  {{- omit . "triggers" "enabled" | toYaml | nindent 2 }}
  triggers:
  {{- range $t := .triggers }}
  - type: {{ $t.type }}
    {{- with $t.metricType}}
    metricType: {{ . }}
    {{- end }}
    {{- if $t.authenticationRef }}
    authenticationRef:
      name: {{ include "mychart.name" $ }}-trigger-authentication
    {{- end }}
    metadata:
      {{- range $key, $value := $t.metadata }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
```
